package com.grvig.financetracker.ui.theme

import androidx.compose.ui.graphics.Color

val GreenPrimary = Color(0xFF2E7D32)
val GreenOnPrimary = Color(0xFFFFFFFF)
val GreenPrimaryContainer = Color(0xFFB8F0B6)
val GreenOnPrimaryContainer = Color(0xFF00210B)
val GreenSecondary = Color(0xFF52634F)
val GreenOnSecondary = Color(0xFFFFFFFF)
val GreenSecondaryContainer = Color(0xFFD5E8CF)
val GreenOnSecondaryContainer = Color(0xFF101F10)
val GreenTertiary = Color(0xFF386667)
val GreenOnTertiary = Color(0xFFFFFFFF)
val GreenTertiaryContainer = Color(0xFFBCEBEC)
val GreenOnTertiaryContainer = Color(0xFF002020)
val GreenBackground = Color(0xFFF8FAF0)
val GreenOnBackground = Color(0xFF1A1C18)
val GreenSurface = Color(0xFFF8FAF0)
val GreenOnSurface = Color(0xFF1A1C18)
val GreenSurfaceVariant = Color(0xFFDEE5D9)
val GreenOnSurfaceVariant = Color(0xFF424940)
val GreenOutline = Color(0xFF72796F)

val GreenPrimaryDark = Color(0xFFA5D6A7)
val GreenOnPrimaryDark = Color(0xFF0B3D14)
val GreenPrimaryContainerDark = Color(0xFF1B5E20)
val GreenOnPrimaryContainerDark = Color(0xFFC8E6C9)
val GreenSecondaryDark = Color(0xFFB9CCB4)
val GreenOnSecondaryDark = Color(0xFF243424)
val GreenSecondaryContainerDark = Color(0xFF3A4A38)
val GreenOnSecondaryContainerDark = Color(0xFFD5E8CF)
val GreenTertiaryDark = Color(0xFFA0CFD0)
val GreenOnTertiaryDark = Color(0xFF003738)
val GreenTertiaryContainerDark = Color(0xFF1E4E4F)
val GreenOnTertiaryContainerDark = Color(0xFFBCEBEC)
val GreenBackgroundDark = Color(0xFF1A1C18)
val GreenOnBackgroundDark = Color(0xFFE2E3DC)
val GreenSurfaceDark = Color(0xFF1A1C18)
val GreenOnSurfaceDark = Color(0xFFE2E3DC)
val GreenSurfaceVariantDark = Color(0xFF424940)
val GreenOnSurfaceVariantDark = Color(0xFFC2C9BD)
val GreenOutlineDark = Color(0xFF8C9388)
